# Debug
DEBUG_ENABLED = False
HITBOX_COLOR = "red"

# Runtime
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_EDGE_PADDING = 60

GAME_TICK = 50.0
MILLI_TO_SECONDS = 1000

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPLIT_ANGLE_MIN = 20
ASTEROID_SPLIT_ANGLE_MAX = 50
ASTEROID_SPLIT_SPEED_MULT = 1.2
ASTEROID_COLOR = "white"
ASTEROID_SPEED_MIN = 40
ASTEROID_SPEED_MAX = 100
ASTEROID_ROTATION_SPEED_MIN = -3
ASTEROID_ROTATION_SPEED_MAX = 3

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_COLOR = "white"
PLAYER_LINE_WIDTH = 2
PLAYER_SHOOT_SPEED = 400
MAX_SHOT_DISTANCE = 1
PLAYER_SHOOT_COOLDOWN = 0.25
PLAYER_MAX_SPEED = 500
PLAYER_ACCELERATE_SPEED = 20
PLAYER_DECELERATE_SPEED = 10

SHOT_RADIUS = 3
SHOT_COLOR = "white"
